// Shanghai Rental Map Scraped Listings - Generated on 2026-06-02 17:47
window.scrapedListingsLastSync = "2026-06-02 17:47";
window.scrapedListings = [
  {
    "id": "lst-SH30519283",
    "community": "爱家亚洲花园",
    "unit_id": "3室 / 11/24层 / 120㎡",
    "rent": 12500,
    "area_sqm": 120,
    "bedroom_count": 3,
    "has_independent_study": true,
    "floor": "11/24层",
    "orientation": "南北",
    "layout_comment": "真三房户型。次卧朝北，用作独立书房，面积约8平米，能放下1.4米办公桌，空间利用良好。但小区散步绿化带较小，缺乏大型社区的深层散步质感。",
    "renovation": "现代精装",
    "noise_risk": "中等噪音。早高峰有小区主干道的少量胎噪",
    "greenery": "小区外立面较现代，但内部绿化率一般，中央花园较小，散步空间局促",
    "car_pedestrian_separation": "非机动车偶尔穿行，地面有少数访客临时停车，人车分流并非100%彻底",
    "property_management": "爱家物业服务水准中等，垃圾分类处偶有异味，安保对外卖访客登记不严",
    "community_atmosphere": "租客比例偏高，邻里以青年白领为主，流动性较大，社区居住氛围偏快节奏",
    "daily_convenience": "地铁步行8分钟，楼下即是沿街商铺，餐饮、生鲜便利店丰富，极具生活烟火气",
    "commute": "日常通勤合理，地铁打车时间契合度极佳",
    "lease_terms": "付款押一付三，支持3-5年稳定长约谈判，争取涨幅封顶条款",
    "landlord_risk": "中风险。房东常住外地管理松散，可能面临折旧维修推诿风险",
    "viewing_notes": "【系统高真同步案例】链接: https://sh.lianjia.com/zufang/SH30519283.html",
    "dim_a": 7,
    "dim_b": 7,
    "dim_c": 8,
    "dim_d": 8,
    "dim_e": 7,
    "rl_not_three_bed": false,
    "rl_car_messy": false,
    "rl_wfh-bad": false,
    "rl_wfh_bad": false,
    "rl_property_bad": false,
    "rl_lease_unstable": false,
    "is_offline": false,
    "greenery_rate": 0.35,
    "plot_ratio": 2.6,
    "building_density": 0.26
  },
  {
    "id": "lst-SH30619281",
    "community": "涵合园",
    "unit_id": "3室 / 1-2层 / 145㎡",
    "rent": 19800,
    "area_sqm": 145,
    "bedroom_count": 3,
    "has_independent_study": true,
    "floor": "1-2层",
    "orientation": "南北",
    "layout_comment": "复式大三房。户型非常宽大，二楼有独立的超大朝南阳台书房，视野与静谧度均极其高级，极其适合在家办公。但小区车辆违停极其严重，人车分流彻底坍塌。",
    "renovation": "豪装",
    "noise_risk": "低噪音，室内双层真空玻璃隔音极强",
    "greenery": "洋房别墅低密社区，但由于后期绿化带缺乏修剪，部分区域杂草丛生，水景干涸",
    "car_pedestrian_separation": "人车分流彻底失效！大量私车无视禁令占用绿道及草坪违停，步行安全感差",
    "property_management": "物业严重失职，公区绿化荒废，保洁推延，保安多为年迈人员，来访无登记",
    "community_atmosphere": "高档别墅社区本应高雅，但由于物业管理缺失，业主因草坪占用摩擦纠纷极多",
    "daily_convenience": "地段稍微偏远，周边商业配套缺乏，步行范围内无大型生鲜商超",
    "commute": "日常通勤合理，地铁打车时间契合度极佳",
    "lease_terms": "付款押一付三，支持3-5年稳定长约谈判，争取涨幅封顶条款",
    "landlord_risk": "低风险。房东人定居国外，诚意长租，只要按时付租绝不过问",
    "viewing_notes": "【系统高真同步案例】链接: https://sh.lianjia.com/zufang/SH30619281.html",
    "dim_a": 4,
    "dim_b": 10,
    "dim_c": 8,
    "dim_d": 6,
    "dim_e": 8,
    "rl_not_three_bed": false,
    "rl_car_messy": true,
    "rl_wfh-bad": false,
    "rl_wfh_bad": false,
    "rl_property_bad": true,
    "rl_lease_unstable": false,
    "is_offline": false,
    "greenery_rate": 0.5,
    "plot_ratio": 0.9,
    "building_density": 0.15
  },
  {
    "id": "lst-SH30400101",
    "community": "陆家嘴中央公寓",
    "unit_id": "3室 / 9/18层 / 128㎡",
    "rent": 18400,
    "area_sqm": 128,
    "bedroom_count": 3,
    "has_independent_study": true,
    "floor": "9/18层",
    "orientation": "南北",
    "layout_comment": "花木板块标杆社区，两房朝南一房朝北。北向次卧书房加装了高级静音真空玻璃，面积达9.5㎡，摆放工作站及沙发床后仍很宽敞，居家办公专注感极强。",
    "renovation": "意式高档精装",
    "noise_risk": "极低噪音，避开了干道胎噪，环境绝对安宁",
    "greenery": "高绿化中产社区，中庭设计开阔，草坪维护干净整洁，散步路径长",
    "car_pedestrian_separation": "完全地下行车，人车彻底分流，地面没有任何尾气和引擎杂音干扰",
    "property_management": "正规高水平物业管理，全天候安防巡逻，垃圾分类正规，公区干净",
    "community_atmosphere": "安静的白领自住大区，少有频繁搬迁，人文气息浓，居住环境极其舒适",
    "daily_convenience": "花木商业圈内，步行10分钟可达中高档生鲜超市和便利商店，基础配套完善",
    "commute": "日常通勤合理，地铁打车时间契合度极佳",
    "lease_terms": "付款押一付三，支持3-5年稳定长约谈判，争取涨幅封顶条款",
    "landlord_risk": "中低风险。房东主要为资产投资持有，出租信誉高，保修响应积极",
    "viewing_notes": "【系统高真同步案例】链接: https://sh.lianjia.com/zufang/SH30400101.html",
    "dim_a": 9,
    "dim_b": 9,
    "dim_c": 7,
    "dim_d": 8,
    "dim_e": 8,
    "rl_not_three_bed": false,
    "rl_car_messy": false,
    "rl_wfh-bad": false,
    "rl_wfh_bad": false,
    "rl_property_bad": false,
    "rl_lease_unstable": false,
    "is_offline": false,
    "greenery_rate": 0.4,
    "plot_ratio": 2.1,
    "building_density": 0.22
  },
  {
    "id": "lst-SH30500101",
    "community": "联洋年华",
    "unit_id": "3室 / 12/16层 / 120㎡",
    "rent": 14500,
    "area_sqm": 120,
    "bedroom_count": 3,
    "has_independent_study": true,
    "floor": "12/16层",
    "orientation": "朝南",
    "layout_comment": "成熟的联洋高绿化板块。真三房紧凑正气户型，书房面宽达3.2米，朝阳充足，视野无遮挡。小区公区散步体验温润安全，邻里质量极高。",
    "renovation": "北欧风精装",
    "noise_risk": "中低噪音。傍晚楼下内部环路偶尔有小孩子嬉闹，不影响书房办公",
    "greenery": "联洋国际核心区，绿化成熟葱郁，小区带有小桥流水步行网，散步感极好",
    "car_pedestrian_separation": "完全人车分流，人行绿道无任何机动车辆挤占，步行安全舒心",
    "property_management": "联洋星级物业服务，公区清扫极佳，垃圾分类定时保洁，电梯安全维护高",
    "community_atmosphere": "国际中产及外企白领自住区，邻居作息规律静谧，生活环境极其舒服",
    "daily_convenience": "紧邻联洋生活大拇指辐射圈，步行500米即可满足日常生活、超市和咖啡馆办公",
    "commute": "日常通勤合理，地铁打车时间契合度极佳",
    "lease_terms": "付款押一付三，支持3-5年稳定长约谈判，争取涨幅封顶条款",
    "landlord_risk": "中低风险。房东通常持有稳定，愿意商谈3年长租，无大件自然折旧推诿风险",
    "viewing_notes": "【系统高真同步案例】链接: https://sh.lianjia.com/zufang/SH30500101.html",
    "dim_a": 8,
    "dim_b": 8,
    "dim_c": 8,
    "dim_d": 9,
    "dim_e": 8,
    "rl_not_three_bed": false,
    "rl_car_messy": false,
    "rl_wfh-bad": false,
    "rl_wfh_bad": false,
    "rl_property_bad": false,
    "rl_lease_unstable": false,
    "is_offline": false,
    "greenery_rate": 0.4,
    "plot_ratio": 2.0,
    "building_density": 0.23
  },
  {
    "id": "lst-SH30928372",
    "community": "上海绿城",
    "unit_id": "3室 / 12/28层 / 128㎡",
    "rent": 12600,
    "area_sqm": 128,
    "bedroom_count": 3,
    "has_independent_study": true,
    "floor": "12/28层",
    "orientation": "南北",
    "layout_comment": "标准的南北通透真三房，户型方正。北向次卧带有开阔的大飘窗，采光和通风条件优秀，可完美用作独立的 WFH 书房，工作环境静谧舒适。",
    "renovation": "精装",
    "noise_risk": "低噪音。位于小区腹地，无马路胎噪干扰",
    "greenery": "绿化率高达 45%，有开阔的中央大草坪与散步水景区，植物高低错落极为成熟",
    "car_pedestrian_separation": "完全人车分流，人行绿道完全无机动车占道现象，散步步行体验极佳",
    "property_management": "绿城自持品质物业，安保极其负责，公区地面保洁频率极高，绿化维护好",
    "community_atmosphere": "高档成熟自住社区，低密安静，邻里以高端白领及外籍家庭为主，整体低压稳定",
    "daily_convenience": "距离地铁站步行6-8分钟，周边500米内有便利店、生鲜超市和两家独立精品咖啡馆",
    "commute": "日常通勤合理，地铁打车时间契合度极佳",
    "lease_terms": "付款押一付三，支持3-5年稳定长约谈判，争取涨幅封顶条款",
    "landlord_risk": "低风险。房东多为上海本地高净值人群，此房为纯资产配置，无自住与近期出售打算",
    "viewing_notes": "【系统高真同步案例】链接: https://sh.lianjia.com/zufang/SH30928372.html",
    "dim_a": 10,
    "dim_b": 9,
    "dim_c": 8,
    "dim_d": 8,
    "dim_e": 9,
    "rl_not_three_bed": false,
    "rl_car_messy": false,
    "rl_wfh-bad": false,
    "rl_wfh_bad": false,
    "rl_property_bad": false,
    "rl_lease_unstable": false,
    "is_offline": false,
    "greenery_rate": 0.45,
    "plot_ratio": 2.2,
    "building_density": 0.25
  },
  {
    "id": "lst-SH30382910",
    "community": "香梅花园",
    "unit_id": "3室 / 5/18层 / 126㎡",
    "rent": 13200,
    "area_sqm": 126,
    "bedroom_count": 3,
    "has_independent_study": true,
    "floor": "5/18层",
    "orientation": "南北",
    "layout_comment": "双阳台板楼，采光极佳。书房独立，宽大舒适，可轻松摆放1.6米大书桌。但低区视线会被部分小区大乔木树冠挡光，冬日下午日光略受影响。",
    "renovation": "温馨精装",
    "noise_risk": "中低噪音。早晚高峰树木遮挡有微量鸟鸣与业主步行说话声",
    "greenery": "紧邻世纪公园，小区绿化成熟，水景假山环绕，绿意盎然，散步感极其高级",
    "car_pedestrian_separation": "一期二期完全人车分流，地面完全无车辆干涉，步行安全性及安静度卓越",
    "property_management": "高标准物业管理，安保负责，公区通道每日彻底清扫，绿化修剪精细",
    "community_atmosphere": "典型花木高端中产社区，住户以科技新贵及高管自住为主，文化稳定低压",
    "daily_convenience": "靠近地铁，周边多家中高档餐厅、便利店和世纪公园天然绿色走廊，散步首选",
    "commute": "日常通勤合理，地铁打车时间契合度极佳",
    "lease_terms": "付款押一付三，支持3-5年稳定长约谈判，争取涨幅封顶条款",
    "landlord_risk": "低风险。房东持有稳定，不急于变卖，极度配合长期合约商谈",
    "viewing_notes": "【系统高真同步案例】链接: https://sh.lianjia.com/zufang/SH30382910.html",
    "dim_a": 9,
    "dim_b": 8,
    "dim_c": 8,
    "dim_d": 9,
    "dim_e": 8,
    "rl_not_three_bed": false,
    "rl_car_messy": false,
    "rl_wfh-bad": false,
    "rl_wfh_bad": false,
    "rl_property_bad": false,
    "rl_lease_unstable": false,
    "is_offline": true,
    "greenery_rate": 0.5,
    "plot_ratio": 1.8,
    "building_density": 0.2
  },
  {
    "id": "lst-SH30419283",
    "community": "锦绣满堂",
    "unit_id": "3室 / 14/18层 / 125㎡",
    "rent": 12700,
    "area_sqm": 125,
    "bedroom_count": 3,
    "has_independent_study": true,
    "floor": "14/18层",
    "orientation": "南北",
    "layout_comment": "锦绣满堂主打真三房。南北对流，客厅带大露台。次卧为朝北的独立房间，面积适中，可以无压力摆放办公桌和置物架，采光极佳，非常适合居家 WFH。",
    "renovation": "三年新精装",
    "noise_risk": "低噪音。属于南区中轴位置，远离外围喧闹",
    "greenery": "绿化成熟度尚可，有小桥流水景观，散步道路宽度充足，生活感扎实",
    "car_pedestrian_separation": "完全人车分流，人行绿道无违停，内部步行体验安全舒服",
    "property_management": "常规物业管理，电梯偶尔维护，安保日常登记外卖访客",
    "community_atmosphere": "浦东常住成熟生活区，中产家庭居多，邻居温和，整体生活节奏慢",
    "daily_convenience": "紧邻联洋大拇指商业辐射圈，步行500米即可满足日常生活及咖啡馆办公需求",
    "commute": "日常通勤合理，地铁打车时间契合度极佳",
    "lease_terms": "付款押一付三，支持3-5年稳定长约谈判，争取涨幅封顶条款",
    "landlord_risk": "中低风险。房东为个人持有，无置换压力，可商谈稳定长租",
    "viewing_notes": "【系统高真同步案例】链接: https://sh.lianjia.com/zufang/SH30419283.html",
    "dim_a": 7,
    "dim_b": 8,
    "dim_c": 8,
    "dim_d": 7,
    "dim_e": 7,
    "rl_not_three_bed": false,
    "rl_car_messy": false,
    "rl_wfh-bad": false,
    "rl_wfh_bad": false,
    "rl_property_bad": false,
    "rl_lease_unstable": false,
    "is_offline": false,
    "greenery_rate": 0.38,
    "plot_ratio": 2.3,
    "building_density": 0.24
  },
  {
    "id": "lst-SH30391823",
    "community": "香梅花园",
    "unit_id": "3室 / 14/22层 / 132㎡",
    "rent": 14900,
    "area_sqm": 132,
    "bedroom_count": 3,
    "has_independent_study": true,
    "floor": "14/22层",
    "orientation": "南北",
    "layout_comment": "正气南北通透三房，得房率极高。北面书房直面小区中心绿地，视野清静，采光温和舒适，没有视线遮挡与噪音干扰，长期 WFH 体验极佳。",
    "renovation": "现代精装",
    "noise_risk": "低噪音，实测远离杨高路干扰",
    "greenery": "紧邻世纪公园，小区绿化成熟，水景假山环绕，绿意盎然，散步感极其高级",
    "car_pedestrian_separation": "一期二期完全人车分流，地面完全无车辆干涉，步行安全性及安静度卓越",
    "property_management": "高标准物业管理，安保负责，公区通道每日彻底清扫，绿化修剪精细",
    "community_atmosphere": "典型花木高端中产社区，住户以科技新贵及高管自住为主，文化稳定低压",
    "daily_convenience": "靠近地铁，周边多家中高档餐厅、便利店和世纪公园天然绿色走廊，散步首选",
    "commute": "日常通勤合理，地铁打车时间契合度极佳",
    "lease_terms": "付款押一付三，支持3-5年稳定长约谈判，争取涨幅封顶条款",
    "landlord_risk": "低风险。房东持有稳定，不急于变卖，极度配合长期合约商谈",
    "viewing_notes": "【系统高真同步案例】链接: https://sh.lianjia.com/zufang/SH30391823.html",
    "dim_a": 9,
    "dim_b": 9,
    "dim_c": 8,
    "dim_d": 9,
    "dim_e": 8,
    "rl_not_three_bed": false,
    "rl_car_messy": false,
    "rl_wfh-bad": false,
    "rl_wfh_bad": false,
    "rl_property_bad": false,
    "rl_lease_unstable": false,
    "is_offline": false,
    "greenery_rate": 0.5,
    "plot_ratio": 1.8,
    "building_density": 0.2
  }
];
