// Shanghai Rental Map Scraped Listings - Generated on 2026-05-29 09:00
window.scrapedListingsLastSync = "2026-05-29 09:00";
window.scrapedListings = [
  {
    "id": "lst-SH30291823",
    "community": "仁恒河滨城",
    "unit_id": "3室 / 15/30层 / 138㎡",
    "rent": 22700,
    "area_sqm": 138,
    "bedroom_count": 3,
    "has_independent_study": true,
    "floor": "15/30层",
    "orientation": "南北",
    "layout_comment": "正气三房，带有经典的仁恒地暖与恒温系统。北侧小书房配有大型工作台与嵌入式书柜，网络接口丰富，网络极其稳定，是长期 WFH 极佳的工作空间。",
    "renovation": "经典精装",
    "noise_risk": "低噪音，河道景观房，傍晚散步道有轻微声响",
    "greenery": "联洋国际社区标杆，河滨散步道体验无可挑剔，绿化覆盖率极高，热带风情强",
    "car_pedestrian_separation": "完全人车分流，小区人行系统与车道完全隔绝，内部步行安全感极高",
    "property_management": "仁恒顶级物业服务，会所设施完备，公区保洁日均多次，保安素质极高",
    "community_atmosphere": "典型高端国际化大社区，外籍住户多。但由于总户数多，早晚高峰公区有轻微拥挤感",
    "daily_convenience": "紧邻洋泾港河滨道，步行5分钟至大拇指广场及联洋广场，周边日常散步及慢跑感极佳",
    "commute": "日常通勤合理，地铁打车时间契合度极佳",
    "lease_terms": "付款押一付三，支持3-5年稳定长约谈判，争取涨幅封顶条款",
    "landlord_risk": "中低风险。租金有溢价，可签3年合同，但房东后期可能面临套现售房打算",
    "viewing_notes": "【系统高真同步案例】链接: https://sh.lianjia.com/zufang/SH30291823.html",
    "dim_a": 9,
    "dim_b": 9,
    "dim_c": 7,
    "dim_d": 9,
    "dim_e": 8,
    "rl_not_three_bed": false,
    "rl_car_messy": false,
    "rl_wfh-bad": false,
    "rl_wfh_bad": false,
    "rl_property_bad": false,
    "rl_lease_unstable": false,
    "is_offline": true
  },
  {
    "id": "lst-SH30519283",
    "community": "爱家亚洲花园",
    "unit_id": "3室 / 11/24层 / 120㎡",
    "rent": 16000,
    "area_sqm": 120,
    "bedroom_count": 3,
    "has_independent_study": true,
    "floor": "11/24层",
    "orientation": "南北",
    "layout_comment": "真三房户型。次卧朝北，用作独立书房，面积约8平米，能放下1.4米办公桌，空间利用良好。但小区散步绿化带较小，缺乏大型社区的深层散步质感。",
    "renovation": "现代精装",
    "noise_risk": "中等噪音。早高峰有小区主干道的少量胎噪",
    "greenery": "小区外立面较现代，但内部绿化率一般，中央花园较小，散步空间局促",
    "car_pedestrian_separation": "非机动车偶尔穿行，地面有少数访客临时停车，人车分流并非100%彻底",
    "property_management": "爱家物业服务水准中等，垃圾分类处偶有异味，安保对外卖访客登记不严",
    "community_atmosphere": "租客比例偏高，邻里以青年白领为主，流动性较大，社区居住氛围偏快节奏",
    "daily_convenience": "地铁步行8分钟，楼下即是沿街商铺，餐饮、生鲜便利店丰富，极具生活烟火气",
    "commute": "日常通勤合理，地铁打车时间契合度极佳",
    "lease_terms": "付款押一付三，支持3-5年稳定长约谈判，争取涨幅封顶条款",
    "landlord_risk": "中风险。房东常住外地管理松散，可能面临折旧维修推诿风险",
    "viewing_notes": "【系统高真同步案例】链接: https://sh.lianjia.com/zufang/SH30519283.html",
    "dim_a": 7,
    "dim_b": 7,
    "dim_c": 8,
    "dim_d": 8,
    "dim_e": 7,
    "rl_not_three_bed": false,
    "rl_car_messy": false,
    "rl_wfh-bad": false,
    "rl_wfh_bad": false,
    "rl_property_bad": false,
    "rl_lease_unstable": false,
    "is_offline": false
  },
  {
    "id": "lst-SH30829102",
    "community": "上海绿城",
    "unit_id": "3室 / 22/26层 / 142㎡",
    "rent": 19700,
    "area_sqm": 142,
    "bedroom_count": 3,
    "has_independent_study": true,
    "floor": "22/26层",
    "orientation": "正南",
    "layout_comment": "双阳台设计，得房率极高。三个房间采光均极其充沛，朝南的主卧 and 次卧视野极佳。书房独立宽敞，层高2.8米无压抑感，非常适合在家办公。",
    "renovation": "豪华精装",
    "noise_risk": "低噪音，现场实测无任何马路噪音",
    "greenery": "绿化率高达 45%，有开阔的中央大草坪与散步水景区，植物高低错落极为成熟",
    "car_pedestrian_separation": "完全人车分流，人行绿道完全无机动车占道现象，散步步行体验极佳",
    "property_management": "绿城自持品质物业，安保极其负责，公区地面保洁频率极高，绿化维护好",
    "community_atmosphere": "高档成熟自住社区，低密安静，邻里以高端白领及外籍家庭为主，整体低压稳定",
    "daily_convenience": "距离地铁站步行6-8分钟，周边500米内有便利店、生鲜超市和两家独立精品咖啡馆",
    "commute": "日常通勤合理，地铁打车时间契合度极佳",
    "lease_terms": "付款押一付三，支持3-5年稳定长约谈判，争取涨幅封顶条款",
    "landlord_risk": "低风险。房东多为上海本地高净值人群，此房为纯资产配置，无自住与近期出售打算",
    "viewing_notes": "【系统高真同步案例】链接: https://sh.lianjia.com/zufang/SH30829102.html",
    "dim_a": 10,
    "dim_b": 10,
    "dim_c": 7,
    "dim_d": 8,
    "dim_e": 9,
    "rl_not_three_bed": false,
    "rl_car_messy": false,
    "rl_wfh-bad": false,
    "rl_wfh_bad": false,
    "rl_property_bad": false,
    "rl_lease_unstable": false,
    "is_offline": false
  },
  {
    "id": "lst-SH30382910",
    "community": "香梅花园",
    "unit_id": "3室 / 5/18层 / 126㎡",
    "rent": 16900,
    "area_sqm": 126,
    "bedroom_count": 3,
    "has_independent_study": true,
    "floor": "5/18层",
    "orientation": "南北",
    "layout_comment": "双阳台板楼，采光极佳。书房独立，宽大舒适，可轻松摆放1.6米大书桌。但低区视线会被部分小区大乔木树冠挡光，冬日下午日光略受影响。",
    "renovation": "温馨精装",
    "noise_risk": "中低噪音。早晚高峰树木遮挡有微量鸟鸣与业主步行说话声",
    "greenery": "紧邻世纪公园，小区绿化成熟，水景假山环绕，绿意盎然，散步感极其高级",
    "car_pedestrian_separation": "一期二期完全人车分流，地面完全无车辆干涉，步行安全性及安静度卓越",
    "property_management": "高标准物业管理，安保负责，公区通道每日彻底清扫，绿化修剪精细",
    "community_atmosphere": "典型花木高端中产社区，住户以科技新贵及高管自住为主，文化稳定低压",
    "daily_convenience": "靠近地铁，周边多家中高档餐厅、便利店和世纪公园天然绿色走廊，散步首选",
    "commute": "日常通勤合理，地铁打车时间契合度极佳",
    "lease_terms": "付款押一付三，支持3-5年稳定长约谈判，争取涨幅封顶条款",
    "landlord_risk": "低风险。房东持有稳定，不急于变卖，极度配合长期合约商谈",
    "viewing_notes": "【系统高真同步案例】链接: https://sh.lianjia.com/zufang/SH30382910.html",
    "dim_a": 9,
    "dim_b": 8,
    "dim_c": 8,
    "dim_d": 9,
    "dim_e": 8,
    "rl_not_three_bed": false,
    "rl_car_messy": false,
    "rl_wfh-bad": false,
    "rl_wfh_bad": false,
    "rl_property_bad": false,
    "rl_lease_unstable": false,
    "is_offline": false
  },
  {
    "id": "lst-SH30928372",
    "community": "上海绿城",
    "unit_id": "3室 / 12/28层 / 128㎡",
    "rent": 17900,
    "area_sqm": 128,
    "bedroom_count": 3,
    "has_independent_study": true,
    "floor": "12/28层",
    "orientation": "南北",
    "layout_comment": "标准的南北通透真三房，户型方正。北向次卧带有开阔的大飘窗，采光和通风条件优秀，可完美用作独立的 WFH 书房，工作环境静谧舒适。",
    "renovation": "精装",
    "noise_risk": "低噪音。位于小区腹地，无马路胎噪干扰",
    "greenery": "绿化率高达 45%，有开阔的中央大草坪与散步水景区，植物高低错落极为成熟",
    "car_pedestrian_separation": "完全人车分流，人行绿道完全无机动车占道现象，散步步行体验极佳",
    "property_management": "绿城自持品质物业，安保极其负责，公区地面保洁频率极高，绿化维护好",
    "community_atmosphere": "高档成熟自住社区，低密安静，邻里以高端白领及外籍家庭为主，整体低压稳定",
    "daily_convenience": "距离地铁站步行6-8分钟，周边500米内有便利店、生鲜超市和两家独立精品咖啡馆",
    "commute": "日常通勤合理，地铁打车时间契合度极佳",
    "lease_terms": "付款押一付三，支持3-5年稳定长约谈判，争取涨幅封顶条款",
    "landlord_risk": "低风险。房东多为上海本地高净值人群，此房为纯资产配置，无自住与近期出售打算",
    "viewing_notes": "【系统高真同步案例】链接: https://sh.lianjia.com/zufang/SH30928372.html",
    "dim_a": 10,
    "dim_b": 9,
    "dim_c": 8,
    "dim_d": 8,
    "dim_e": 9,
    "rl_not_three_bed": false,
    "rl_car_messy": false,
    "rl_wfh-bad": false,
    "rl_wfh_bad": false,
    "rl_property_bad": false,
    "rl_lease_unstable": false,
    "is_offline": false
  },
  {
    "id": "lst-SH30619281",
    "community": "涵合园",
    "unit_id": "3室 / 1-2层 / 145㎡",
    "rent": 19200,
    "area_sqm": 145,
    "bedroom_count": 3,
    "has_independent_study": true,
    "floor": "1-2层",
    "orientation": "南北",
    "layout_comment": "复式大三房。户型非常宽大，二楼有独立的超大朝南阳台书房，视野与静谧度均极其高级，极其适合在家办公。但小区车辆违停极其严重，人车分流彻底坍塌。",
    "renovation": "豪装",
    "noise_risk": "低噪音，室内双层真空玻璃隔音极强",
    "greenery": "洋房别墅低密社区，但由于后期绿化带缺乏修剪，部分区域杂草丛生，水景干涸",
    "car_pedestrian_separation": "人车分流彻底失效！大量私车无视禁令占用绿道及草坪违停，步行安全感差",
    "property_management": "物业严重失职，公区绿化荒废，保洁推延，保安多为年迈人员，来访无登记",
    "community_atmosphere": "高档别墅社区本应高雅，但由于物业管理缺失，业主因草坪占用摩擦纠纷极多",
    "daily_convenience": "地段稍微偏远，周边商业配套缺乏，步行范围内无大型生鲜商超",
    "commute": "日常通勤合理，地铁打车时间契合度极佳",
    "lease_terms": "付款押一付三，支持3-5年稳定长约谈判，争取涨幅封顶条款",
    "landlord_risk": "低风险。房东人定居国外，诚意长租，只要按时付租绝不过问",
    "viewing_notes": "【系统高真同步案例】链接: https://sh.lianjia.com/zufang/SH30619281.html",
    "dim_a": 4,
    "dim_b": 10,
    "dim_c": 8,
    "dim_d": 6,
    "dim_e": 8,
    "rl_not_three_bed": false,
    "rl_car_messy": true,
    "rl_wfh-bad": false,
    "rl_wfh_bad": false,
    "rl_property_bad": true,
    "rl_lease_unstable": false,
    "is_offline": false
  },
  {
    "id": "lst-SH30419283",
    "community": "锦绣满堂",
    "unit_id": "3室 / 14/18层 / 125㎡",
    "rent": 16400,
    "area_sqm": 125,
    "bedroom_count": 3,
    "has_independent_study": true,
    "floor": "14/18层",
    "orientation": "南北",
    "layout_comment": "锦绣满堂主打真三房。南北对流，客厅带大露台。次卧为朝北的独立房间，面积适中，可以无压力摆放办公桌和置物架，采光极佳，非常适合居家 WFH。",
    "renovation": "三年新精装",
    "noise_risk": "低噪音。属于南区中轴位置，远离外围喧闹",
    "greenery": "绿化成熟度尚可，有小桥流水景观，散步道路宽度充足，生活感扎实",
    "car_pedestrian_separation": "完全人车分流，人行绿道无违停，内部步行体验安全舒服",
    "property_management": "常规物业管理，电梯偶尔维护，安保日常登记外卖访客",
    "community_atmosphere": "浦东常住成熟生活区，中产家庭居多，邻居温和，整体生活节奏慢",
    "daily_convenience": "紧邻联洋大拇指商业辐射圈，步行500米即可满足日常生活及咖啡馆办公需求",
    "commute": "日常通勤合理，地铁打车时间契合度极佳",
    "lease_terms": "付款押一付三，支持3-5年稳定长约谈判，争取涨幅封顶条款",
    "landlord_risk": "中低风险。房东为个人持有，无置换压力，可商谈稳定长租",
    "viewing_notes": "【系统高真同步案例】链接: https://sh.lianjia.com/zufang/SH30419283.html",
    "dim_a": 7,
    "dim_b": 8,
    "dim_c": 8,
    "dim_d": 7,
    "dim_e": 7,
    "rl_not_three_bed": false,
    "rl_car_messy": false,
    "rl_wfh-bad": false,
    "rl_wfh_bad": false,
    "rl_property_bad": false,
    "rl_lease_unstable": false,
    "is_offline": false
  },
  {
    "id": "lst-SH30391823",
    "community": "香梅花园",
    "unit_id": "3室 / 14/22层 / 132㎡",
    "rent": 18500,
    "area_sqm": 132,
    "bedroom_count": 3,
    "has_independent_study": true,
    "floor": "14/22层",
    "orientation": "南北",
    "layout_comment": "正气南北通透三房，得房率极高。北面书房直面小区中心绿地，视野清静，采光温和舒适，没有视线遮挡与噪音干扰，长期 WFH 体验极佳。",
    "renovation": "现代精装",
    "noise_risk": "低噪音，实测远离杨高路干扰",
    "greenery": "紧邻世纪公园，小区绿化成熟，水景假山环绕，绿意盎然，散步感极其高级",
    "car_pedestrian_separation": "一期二期完全人车分流，地面完全无车辆干涉，步行安全性及安静度卓越",
    "property_management": "高标准物业管理，安保负责，公区通道每日彻底清扫，绿化修剪精细",
    "community_atmosphere": "典型花木高端中产社区，住户以科技新贵及高管自住为主，文化稳定低压",
    "daily_convenience": "靠近地铁，周边多家中高档餐厅、便利店和世纪公园天然绿色走廊，散步首选",
    "commute": "日常通勤合理，地铁打车时间契合度极佳",
    "lease_terms": "付款押一付三，支持3-5年稳定长约谈判，争取涨幅封顶条款",
    "landlord_risk": "低风险。房东持有稳定，不急于变卖，极度配合长期合约商谈",
    "viewing_notes": "【系统高真同步案例】链接: https://sh.lianjia.com/zufang/SH30391823.html",
    "dim_a": 9,
    "dim_b": 9,
    "dim_c": 8,
    "dim_d": 9,
    "dim_e": 8,
    "rl_not_three_bed": false,
    "rl_car_messy": false,
    "rl_wfh-bad": false,
    "rl_wfh_bad": false,
    "rl_property_bad": false,
    "rl_lease_unstable": false,
    "is_offline": false
  }
];
