// Shanghai Rental Map Scraped Listings - Generated on 2026-07-02 09:00
window.scrapedListingsLastSync = "2026-07-02 09:00";
window.scrapedListings = [
  {
    "id": "lst-SH30419283",
    "community": "锦绣满堂",
    "unit_id": "3室 / 14/18层 / 125㎡",
    "rent": 12800,
    "area_sqm": 125,
    "bedroom_count": 3,
    "has_independent_study": true,
    "floor": "14/18层",
    "orientation": "南北",
    "layout_comment": "锦绣满堂主打真三房。南北对流，客厅带大露台。次卧为朝北的独立房间，面积适中，可以无压力摆放办公桌和置物架，采光极佳，非常适合居家 WFH。",
    "renovation": "三年新精装",
    "noise_risk": "低噪音。属于南区中轴位置，远离外围喧闹",
    "greenery": "绿化成熟度尚可，有小桥流水景观，散步道路宽度充足，生活感扎实",
    "car_pedestrian_separation": "完全人车分流，人行绿道无违停，内部步行体验安全舒服",
    "property_management": "常规物业管理，电梯偶尔维护，安保日常登记外卖访客",
    "community_atmosphere": "浦东常住成熟生活区，中产家庭居多，邻居温和，整体生活节奏慢",
    "daily_convenience": "紧邻联洋大拇指商业辐射圈，步行500米即可满足日常生活及咖啡馆办公需求",
    "commute": "【每周3天·陆家嘴环球金融中心】🚇 9号线世纪大道换2号线至陆家嘴（约38-48分钟） | 🚌 不建议依赖公交 | 🚗 锦绣路 → 内环 → 陆家嘴（平峰约22分，早高峰约40分）",
    "commute_metro": "9号线世纪大道换2号线至陆家嘴（约38-48分钟）",
    "commute_bus": "不建议依赖公交",
    "commute_drive": "锦绣路 → 内环 → 陆家嘴（平峰约22分，早高峰约40分）",
    "commute_parking": "SWFC停车约15元/60分钟",
    "commute_peak_metro_min": 43,
    "commute_peak_drive_min": 40,
    "commute_score_swfc": 8,
    "lease_terms": "付款押一付三，支持3-5年稳定长约谈判，争取涨幅封顶条款",
    "landlord_risk": "中低风险。房东为个人持有，无置换压力，可商谈稳定长租",
    "viewing_notes": "【系统高真同步案例】链接: https://sh.lianjia.com/zufang/SH30419283.html",
    "dim_a": 7,
    "dim_b": 8,
    "dim_c": 8,
    "dim_d": 7,
    "dim_e": 7,
    "rl_not_three_bed": false,
    "rl_car_messy": false,
    "rl_wfh-bad": false,
    "rl_wfh_bad": false,
    "rl_property_bad": false,
    "rl_lease_unstable": false,
    "is_offline": false,
    "greenery_rate": 0.38,
    "plot_ratio": 2.3,
    "building_density": 0.24
  },
  {
    "id": "lst-SH30782910",
    "community": "四季雅苑",
    "unit_id": "3室 / 8/12层 / 128㎡",
    "rent": 16600,
    "area_sqm": 128,
    "bedroom_count": 3,
    "has_independent_study": true,
    "floor": "8/12层",
    "orientation": "南北",
    "layout_comment": "花木世纪公园旁和黄低密社区内公寓三房，南北通透正气。北向次卧可作独立书房，窗景面向内部浓荫绿地，安静度与采光均优，极适合长期 WFH。需现场确认楼栋入口是否有台阶——部分低密组团对轮椅推行不够友好。",
    "renovation": "经典精装保养良好",
    "noise_risk": "极低噪音，远离主干道，内部环路仅有偶发邻里步行声",
    "greenery": "和记黄埔打造的花木低密标杆，绿化率高达55%，内部林荫步道与中央绿地极具散步质感，紧邻世纪公园延伸绿廊",
    "car_pedestrian_separation": "低密别墅区人车分流严格，主干道车流极少，步行环道安静安全",
    "property_management": "和记物业口碑稳定，公区保洁与绿化修剪频率高，门禁与访客管理较严",
    "community_atmosphere": "高端自住为主，外籍与高管家庭占比高，社区氛围安静有序，整体熵值极低",
    "daily_convenience": "步行可达世纪公园与大拇指广场，2号线世纪公园站约800-1000米，生活医疗配套成熟",
    "commute": "【每周3天·陆家嘴环球金融中心】🚇 步行世纪公园站 → 2号线陆家嘴站 → 步行至环球金融中心（约32-42分钟） | 🚌 983/987路转2号线；高峰约45-60分钟，雨天备选 | 🚗 花木路 → 内环 → 陆家嘴环路（平峰约22分，早高峰约42分）",
    "commute_metro": "步行世纪公园站 → 2号线陆家嘴站 → 步行至环球金融中心（约32-42分钟）",
    "commute_bus": "983/987路转2号线；高峰约45-60分钟，雨天备选",
    "commute_drive": "花木路 → 内环 → 陆家嘴环路（平峰约22分，早高峰约42分）",
    "commute_parking": "SWFC停车约15元/60分钟",
    "commute_peak_metro_min": 38,
    "commute_peak_drive_min": 42,
    "commute_score_swfc": 8,
    "lease_terms": "付款押一付三，支持3-5年稳定长约谈判，争取涨幅封顶条款",
    "landlord_risk": "中低风险。标的稀缺租金偏高，多数房东持有多套资产，愿意谈3年长约但难锁不涨租",
    "viewing_notes": "【系统高真同步案例】链接: https://sh.lianjia.com/zufang/SH30782910.html",
    "dim_a": 10,
    "dim_b": 8,
    "dim_c": 7,
    "dim_d": 9,
    "dim_e": 8,
    "rl_not_three_bed": false,
    "rl_car_messy": false,
    "rl_wfh-bad": false,
    "rl_wfh_bad": false,
    "rl_property_bad": false,
    "rl_lease_unstable": false,
    "is_offline": false,
    "greenery_rate": 0.55,
    "plot_ratio": 0.38,
    "building_density": 0.12
  },
  {
    "id": "lst-SH30391823",
    "community": "香梅花园",
    "unit_id": "3室 / 14/22层 / 132㎡",
    "rent": 14900,
    "area_sqm": 132,
    "bedroom_count": 3,
    "has_independent_study": true,
    "floor": "14/22层",
    "orientation": "南北",
    "layout_comment": "正气南北通透三房，得房率极高。北面书房直面小区中心绿地，视野清静，采光温和舒适，没有视线遮挡与噪音干扰，长期 WFH 体验极佳。",
    "renovation": "现代精装",
    "noise_risk": "低噪音，实测远离杨高路干扰",
    "greenery": "紧邻世纪公园，小区绿化成熟，水景假山环绕，绿意盎然，散步感极其高级",
    "car_pedestrian_separation": "一期二期完全人车分流，地面完全无车辆干涉，步行安全性及安静度卓越",
    "property_management": "高标准物业管理，安保负责，公区通道每日彻底清扫，绿化修剪精细",
    "community_atmosphere": "典型花木高端中产社区，住户以科技新贵及高管自住为主，文化稳定低压",
    "daily_convenience": "靠近地铁，周边多家中高档餐厅、便利店和世纪公园天然绿色走廊，散步首选",
    "commute": "【每周3天·陆家嘴环球金融中心】🚇 世纪公园站2号线直达陆家嘴（约28-38分钟） | 🚌 东周线/794至东昌路，高峰约45-55分钟 | 🚗 梅花路 → 内环 → 陆家嘴（平峰约18分，早高峰约35分）",
    "commute_metro": "世纪公园站2号线直达陆家嘴（约28-38分钟）",
    "commute_bus": "东周线/794至东昌路，高峰约45-55分钟",
    "commute_drive": "梅花路 → 内环 → 陆家嘴（平峰约18分，早高峰约35分）",
    "commute_parking": "SWFC停车约15元/60分钟",
    "commute_peak_metro_min": 33,
    "commute_peak_drive_min": 35,
    "commute_score_swfc": 9,
    "lease_terms": "付款押一付三，支持3-5年稳定长约谈判，争取涨幅封顶条款",
    "landlord_risk": "低风险。房东持有稳定，不急于变卖，极度配合长期合约商谈",
    "viewing_notes": "【系统高真同步案例】链接: https://sh.lianjia.com/zufang/SH30391823.html",
    "dim_a": 9,
    "dim_b": 9,
    "dim_c": 8,
    "dim_d": 9,
    "dim_e": 8,
    "rl_not_three_bed": false,
    "rl_car_messy": false,
    "rl_wfh-bad": false,
    "rl_wfh_bad": false,
    "rl_property_bad": false,
    "rl_lease_unstable": false,
    "is_offline": false,
    "greenery_rate": 0.5,
    "plot_ratio": 1.8,
    "building_density": 0.2
  },
  {
    "id": "lst-SH30500101",
    "community": "联洋年华",
    "unit_id": "3室 / 12/16层 / 120㎡",
    "rent": 14600,
    "area_sqm": 120,
    "bedroom_count": 3,
    "has_independent_study": true,
    "floor": "12/16层",
    "orientation": "朝南",
    "layout_comment": "成熟的联洋高绿化板块。真三房紧凑正气户型，书房面宽达3.2米，朝阳充足，视野无遮挡。小区公区散步体验温润安全，邻里质量极高。",
    "renovation": "北欧风精装",
    "noise_risk": "中低噪音。傍晚楼下内部环路偶尔有小孩子嬉闹，不影响书房办公",
    "greenery": "联洋国际核心区，绿化成熟葱郁，小区带有小桥流水步行网，散步感极好",
    "car_pedestrian_separation": "完全人车分流，人行绿道无任何机动车辆挤占，步行安全舒心",
    "property_management": "联洋星级物业服务，公区清扫极佳，垃圾分类定时保洁，电梯安全维护高",
    "community_atmosphere": "国际中产及外企白领自住区，邻居作息规律静谧，生活环境极其舒服",
    "daily_convenience": "紧邻联洋生活大拇指辐射圈，步行500米即可满足日常生活、超市和咖啡馆办公",
    "commute": "【每周3天·陆家嘴环球金融中心】🚇 9号线世纪大道换2号线至陆家嘴（约35-45分钟） | 🚌 不建议依赖公交 | 🚗 芳甸路 → 内环 → 陆家嘴（平峰约20分，早高峰约38分）",
    "commute_metro": "9号线世纪大道换2号线至陆家嘴（约35-45分钟）",
    "commute_bus": "不建议依赖公交",
    "commute_drive": "芳甸路 → 内环 → 陆家嘴（平峰约20分，早高峰约38分）",
    "commute_parking": "SWFC停车约15元/60分钟",
    "commute_peak_metro_min": 40,
    "commute_peak_drive_min": 38,
    "commute_score_swfc": 8,
    "lease_terms": "付款押一付三，支持3-5年稳定长约谈判，争取涨幅封顶条款",
    "landlord_risk": "中低风险。房东通常持有稳定，愿意商谈3年长租，无大件自然折旧推诿风险",
    "viewing_notes": "【系统高真同步案例】链接: https://sh.lianjia.com/zufang/SH30500101.html",
    "dim_a": 8,
    "dim_b": 8,
    "dim_c": 8,
    "dim_d": 9,
    "dim_e": 8,
    "rl_not_three_bed": false,
    "rl_car_messy": false,
    "rl_wfh-bad": false,
    "rl_wfh_bad": false,
    "rl_property_bad": false,
    "rl_lease_unstable": false,
    "is_offline": false,
    "greenery_rate": 0.4,
    "plot_ratio": 2.0,
    "building_density": 0.23
  },
  {
    "id": "lst-SH30519283",
    "community": "爱家亚洲花园",
    "unit_id": "3室 / 11/24层 / 120㎡",
    "rent": 12500,
    "area_sqm": 120,
    "bedroom_count": 3,
    "has_independent_study": true,
    "floor": "11/24层",
    "orientation": "南北",
    "layout_comment": "真三房户型。次卧朝北，用作独立书房，面积约8平米，能放下1.4米办公桌，空间利用良好。但小区散步绿化带较小，缺乏大型社区的深层散步质感。",
    "renovation": "现代精装",
    "noise_risk": "中等噪音。早高峰有小区主干道的少量胎噪",
    "greenery": "小区外立面较现代，但内部绿化率一般，中央花园较小，散步空间局促",
    "car_pedestrian_separation": "非机动车偶尔穿行，地面有少数访客临时停车，人车分流并非100%彻底",
    "property_management": "爱家物业服务水准中等，垃圾分类处偶有异味，安保对外卖访客登记不严",
    "community_atmosphere": "租客比例偏高，邻里以青年白领为主，流动性较大，社区居住氛围偏快节奏",
    "daily_convenience": "地铁步行8分钟，楼下即是沿街商铺，餐饮、生鲜便利店丰富，极具生活烟火气",
    "commute": "【每周3天·陆家嘴环球金融中心】🚇 6号线世纪大道换2号线至陆家嘴（约45-55分钟） | 🚌 781/610至浦东南路，高峰约50-70分钟 | 🚗 浦三路 → 内环 → 陆家嘴（平峰约22分，早高峰约45分）",
    "commute_metro": "6号线世纪大道换2号线至陆家嘴（约45-55分钟）",
    "commute_bus": "781/610至浦东南路，高峰约50-70分钟",
    "commute_drive": "浦三路 → 内环 → 陆家嘴（平峰约22分，早高峰约45分）",
    "commute_parking": "SWFC停车约15元/60分钟",
    "commute_peak_metro_min": 50,
    "commute_peak_drive_min": 45,
    "commute_score_swfc": 7,
    "lease_terms": "付款押一付三，支持3-5年稳定长约谈判，争取涨幅封顶条款",
    "landlord_risk": "中风险。房东常住外地管理松散，可能面临折旧维修推诿风险",
    "viewing_notes": "【系统高真同步案例】链接: https://sh.lianjia.com/zufang/SH30519283.html",
    "dim_a": 7,
    "dim_b": 7,
    "dim_c": 8,
    "dim_d": 8,
    "dim_e": 7,
    "rl_not_three_bed": false,
    "rl_car_messy": false,
    "rl_wfh-bad": false,
    "rl_wfh_bad": false,
    "rl_property_bad": false,
    "rl_lease_unstable": false,
    "is_offline": false,
    "greenery_rate": 0.35,
    "plot_ratio": 2.6,
    "building_density": 0.26
  },
  {
    "id": "lst-SH30928372",
    "community": "上海绿城",
    "unit_id": "3室 / 12/28层 / 128㎡",
    "rent": 12300,
    "area_sqm": 128,
    "bedroom_count": 3,
    "has_independent_study": true,
    "floor": "12/28层",
    "orientation": "南北",
    "layout_comment": "标准的南北通透真三房，户型方正。北向次卧带有开阔的大飘窗，采光和通风条件优秀，可完美用作独立的 WFH 书房，工作环境静谧舒适。",
    "renovation": "精装",
    "noise_risk": "低噪音。位于小区腹地，无马路胎噪干扰",
    "greenery": "绿化率高达 45%，有开阔的中央大草坪与散步水景区，植物高低错落极为成熟",
    "car_pedestrian_separation": "完全人车分流，人行绿道完全无机动车占道现象，散步步行体验极佳",
    "property_management": "绿城自持品质物业，安保极其负责，公区地面保洁频率极高，绿化维护好",
    "community_atmosphere": "高档成熟自住社区，低密安静，邻里以高端白领及外籍家庭为主，整体低压稳定",
    "daily_convenience": "距离地铁站步行6-8分钟，周边500米内有便利店、生鲜超市和两家独立精品咖啡馆",
    "commute": "【每周3天·陆家嘴环球金融中心】🚇 7号线龙阳路换2号线至陆家嘴（约40-50分钟） | 🚌 794/东周线至陆家嘴环路段，高峰约50-65分钟 | 🚗 锦绣路 → 内环 → 陆家嘴（平峰约25分，早高峰约45分）",
    "commute_metro": "7号线龙阳路换2号线至陆家嘴（约40-50分钟）",
    "commute_bus": "794/东周线至陆家嘴环路段，高峰约50-65分钟",
    "commute_drive": "锦绣路 → 内环 → 陆家嘴（平峰约25分，早高峰约45分）",
    "commute_parking": "SWFC停车约15元/60分钟",
    "commute_peak_metro_min": 45,
    "commute_peak_drive_min": 45,
    "commute_score_swfc": 7,
    "lease_terms": "付款押一付三，支持3-5年稳定长约谈判，争取涨幅封顶条款",
    "landlord_risk": "低风险。房东多为上海本地高净值人群，此房为纯资产配置，无自住与近期出售打算",
    "viewing_notes": "【系统高真同步案例】链接: https://sh.lianjia.com/zufang/SH30928372.html",
    "dim_a": 10,
    "dim_b": 9,
    "dim_c": 8,
    "dim_d": 8,
    "dim_e": 9,
    "rl_not_three_bed": false,
    "rl_car_messy": false,
    "rl_wfh-bad": false,
    "rl_wfh_bad": false,
    "rl_property_bad": false,
    "rl_lease_unstable": false,
    "is_offline": true,
    "greenery_rate": 0.45,
    "plot_ratio": 2.2,
    "building_density": 0.25
  },
  {
    "id": "lst-SH30291823",
    "community": "仁恒河滨城",
    "unit_id": "3室 / 15/30层 / 138㎡",
    "rent": 19500,
    "area_sqm": 138,
    "bedroom_count": 3,
    "has_independent_study": true,
    "floor": "15/30层",
    "orientation": "南北",
    "layout_comment": "正气三房，带有经典的仁恒地暖与恒温系统。北侧小书房配有大型工作台与嵌入式书柜，网络接口丰富，网络极其稳定，是长期 WFH 极佳的工作空间。",
    "renovation": "经典精装",
    "noise_risk": "低噪音，河道景观房，傍晚散步道有轻微声响",
    "greenery": "联洋国际社区标杆，河滨散步道体验无可挑剔，绿化覆盖率极高，热带风情强",
    "car_pedestrian_separation": "完全人车分流，小区人行系统与车道完全隔绝，内部步行安全感极高",
    "property_management": "仁恒顶级物业服务，会所设施完备，公区保洁日均多次，保安素质极高",
    "community_atmosphere": "典型高端国际化大社区，外籍住户多。但由于总户数多，早晚高峰公区有轻微拥挤感",
    "daily_convenience": "紧邻洋泾港河滨道，步行5分钟至大拇指广场及联洋广场，周边日常散步及慢跑感极佳",
    "commute": "【每周3天·陆家嘴环球金融中心】🚇 9号线世纪大道换2号线至陆家嘴（约35-45分钟） | 🚌 公交稀疏，建议地铁或打车接驳 | 🚗 罗山路 → 内环 → 陆家嘴（平峰约20分，早高峰约38分）",
    "commute_metro": "9号线世纪大道换2号线至陆家嘴（约35-45分钟）",
    "commute_bus": "公交稀疏，建议地铁或打车接驳",
    "commute_drive": "罗山路 → 内环 → 陆家嘴（平峰约20分，早高峰约38分）",
    "commute_parking": "SWFC停车约15元/60分钟",
    "commute_peak_metro_min": 40,
    "commute_peak_drive_min": 38,
    "commute_score_swfc": 8,
    "lease_terms": "付款押一付三，支持3-5年稳定长约谈判，争取涨幅封顶条款",
    "landlord_risk": "中低风险。租金有溢价，可签3年合同，但房东后期可能面临套现售房打算",
    "viewing_notes": "【系统高真同步案例】链接: https://sh.lianjia.com/zufang/SH30291823.html",
    "dim_a": 9,
    "dim_b": 9,
    "dim_c": 7,
    "dim_d": 9,
    "dim_e": 8,
    "rl_not_three_bed": false,
    "rl_car_messy": false,
    "rl_wfh-bad": false,
    "rl_wfh_bad": false,
    "rl_property_bad": false,
    "rl_lease_unstable": false,
    "is_offline": false,
    "greenery_rate": 0.6,
    "plot_ratio": 2.7,
    "building_density": 0.18
  },
  {
    "id": "lst-SH30400101",
    "community": "陆家嘴中央公寓",
    "unit_id": "3室 / 9/18层 / 128㎡",
    "rent": 18500,
    "area_sqm": 128,
    "bedroom_count": 3,
    "has_independent_study": true,
    "floor": "9/18层",
    "orientation": "南北",
    "layout_comment": "花木板块标杆社区，两房朝南一房朝北。北向次卧书房加装了高级静音真空玻璃，面积达9.5㎡，摆放工作站及沙发床后仍很宽敞，居家办公专注感极强。",
    "renovation": "意式高档精装",
    "noise_risk": "极低噪音，避开了干道胎噪，环境绝对安宁",
    "greenery": "高绿化中产社区，中庭设计开阔，草坪维护干净整洁，散步路径长",
    "car_pedestrian_separation": "完全地下行车，人车彻底分流，地面没有任何尾气和引擎杂音干扰",
    "property_management": "正规高水平物业管理，全天候安防巡逻，垃圾分类正规，公区干净",
    "community_atmosphere": "安静的白领自住大区，少有频繁搬迁，人文气息浓，居住环境极其舒适",
    "daily_convenience": "花木商业圈内，步行10分钟可达中高档生鲜超市和便利商店，基础配套完善",
    "commute": "【每周3天·陆家嘴环球金融中心】🚇 2号线直达陆家嘴（约25-35分钟） | 🚌 796/583至东昌路，高峰约35-50分钟 | 🚗 锦带路 → 内环 → 陆家嘴（平峰约15分，早高峰约32分）",
    "commute_metro": "2号线直达陆家嘴（约25-35分钟）",
    "commute_bus": "796/583至东昌路，高峰约35-50分钟",
    "commute_drive": "锦带路 → 内环 → 陆家嘴（平峰约15分，早高峰约32分）",
    "commute_parking": "SWFC停车约15元/60分钟",
    "commute_peak_metro_min": 30,
    "commute_peak_drive_min": 32,
    "commute_score_swfc": 9,
    "lease_terms": "付款押一付三，支持3-5年稳定长约谈判，争取涨幅封顶条款",
    "landlord_risk": "中低风险。房东主要为资产投资持有，出租信誉高，保修响应积极",
    "viewing_notes": "【系统高真同步案例】链接: https://sh.lianjia.com/zufang/SH30400101.html",
    "dim_a": 9,
    "dim_b": 9,
    "dim_c": 7,
    "dim_d": 8,
    "dim_e": 8,
    "rl_not_three_bed": false,
    "rl_car_messy": false,
    "rl_wfh-bad": false,
    "rl_wfh_bad": false,
    "rl_property_bad": false,
    "rl_lease_unstable": false,
    "is_offline": false,
    "greenery_rate": 0.4,
    "plot_ratio": 2.1,
    "building_density": 0.22
  }
];
